cc=arm-xilinx-linux-gnueabi-g++

all:
	$(cc) test.cpp  libzxing_arm.a -I./ -I/opt/CodeSourcery/opencv-2.4.8/include/ -L/opt/CodeSourcery/opencv-2.4.8/lib -lopencv_imgproc 	-lopencv_core -lopencv_highgui 
	#-lopencv_imgcodecs
