######################################################################
# Automatically generated by qmake (3.0) Mon Jun 26 01:32:00 2017
######################################################################

TEMPLATE = app
TARGET = OpenGLWindow
INCLUDEPATH += .

# Input
HEADERS += OpenGLWindow.hpp
SOURCES += OpenGLWindow.cpp
